# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07ff7e71922bc3c2820c11fcc884f061f11a428a2bb164e7620156f883e0e896fc7cf2290617631af813ecabd18cf70b0f58f648654054fedb5fd2e354f0327f

test:
  secret_key_base: 819aa47f311458fa27cd4970feb9df62413ee413a2c7760827eda1f342fc7f5a2124cc40813d5d078fa1c9e067742929c6e8951d3cb4d0a06bbb8768f14c5cc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
